[package]
name = "openid"
version = "0.12.0"
authors = ["Alexander Korolev <alexander.korolev.germany@gmail.com>"]
edition = "2021"
categories = ["authentication"]
description = """
OpenID Connect & Discovery client library using async / await.
"""
homepage = "https://github.com/kilork/openid"
keywords = ["authentication", "authorization", "oauth", "openid", "uma2"]
license = "Unlicense OR MIT"
readme = "README.md"
repository = "https://github.com/kilork/openid"
rust-version = "1.65"

[features]
default = ["native-tls"]
microsoft = []
uma2 = []
native-tls = ["reqwest/native-tls"]
rustls = ["reqwest/rustls-tls"]
middleware = ["reqwest-maybe-middleware/middleware"]

[dependencies]
lazy_static = "1.4"
serde_json = { version = "1", default-features = false }
base64 = "0.21"
biscuit = "0.6"
thiserror = "1"
validator = { version = "0.16", features = ["derive"] }
mime = "0.3"
reqwest-maybe-middleware = "0.2.1"

[dependencies.url]
version = "2"
default-features = false
features = ["serde"]

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["serde"]

[dependencies.serde]
version = "1"
default-features = false
features = ["derive"]

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json"]
